---

- name: minha primeira playbook
  hosts: all
  tasks: 
   - name: adicionando usuario devops
     user:
      name: devops
      password: '$1$sjL/czHD$H6QKiraFRSUp0tPeOnEnh0'
      shell: /bin/bash		
